-- Table: public.User

-- DROP TABLE public."User";

CREATE TABLE public."User"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default",
    "Surname" text COLLATE pg_catalog."default",
    "Email" text COLLATE pg_catalog."default",
    "PasswordHash" bytea,
    "PasswordSalt" bytea,
    CONSTRAINT "User_pkey" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."User"
    OWNER to postgres;